#!/usr/bin/env python3
"""OSS Singularity contract lab (roadmap stage 05, first slice).

Turns ONE synthetic milestone agreement (roles, a delivery digest, an
acceptance policy and a deadline) into a readable delivery-and-acceptance
Solidity example plus a plain-language explanation of every function and
requested signature. Deterministic: the same agreement always produces
byte-identical output, so a pinned commit reproduces the generated files.

The lab explains signatures; it never requests one from a wallet, never
deploys, and never touches funds. Inputs are synthetic placeholders.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SOLIDITY_VERSION = "^0.8.24"


def load_agreement(source: str) -> dict:
    document = json.loads(Path(source).read_text(encoding="utf-8"))
    if document.get("kind") != "oss-solidity-lab-agreement" or document.get("schema_version") != 1:
        raise ValueError("not an oss-solidity-lab-agreement (schema_version 1)")
    for field in ("contributor", "coordinator", "delivery_digest", "deadline"):
        if field not in document:
            raise ValueError(f"agreement is missing {field}")
    digest = document["delivery_digest"]
    if not isinstance(digest, str) or len(digest) != 64 or any(c not in "0123456789abcdef" for c in digest):
        raise ValueError("delivery_digest must be 64 lowercase hex characters")
    if not isinstance(document["deadline"], int) or document["deadline"] <= 0:
        raise ValueError("deadline must be a positive integer timestamp")
    return document


def contract_source(agreement: dict) -> str:
    return f"""// SPDX-License-Identifier: MIT
// Generated by the OSS Singularity contract lab (roadmap stage 05 first slice).
// SYNTHETIC EXAMPLE — {agreement['title']}. Placeholder addresses, a digest
// over the public synthetic artifact and a future deadline; no funds, no
// deployment, no wallet. The lab explains every requested signature; it never
// requests one. Nothing signs or deploys merely because this file exists.
pragma solidity {SOLIDITY_VERSION};

/// @title DeliveryAcceptance — a readable delivery-and-acceptance example.
/// @notice Mirrors the coordination protocol: a contributor delivers immutable
///         revisions, the coordinator requests a revision or accepts exactly
///         the newest one before a deadline. Acceptance completes the record;
///         nothing here transfers value of any kind.
contract DeliveryAcceptance {{
    // ---- Roles from the agreement (synthetic placeholders) ----
    address public immutable contributor = {agreement['contributor']};
    address public immutable coordinator = {agreement['coordinator']};

    // ---- Delivery reference: sha256 over the delivered bytes ----
    // The manifest digest of the synthetic artifact this example stands for.
    bytes32 public constant DECLARED_DIGEST = 0x{agreement['delivery_digest']};

    // ---- Acceptance policy ----
    uint256 public constant DEADLINE = {agreement['deadline']};

    // ---- Review state: one revision at a time, immutable once recorded ----
    uint16 public currentRevision;          // 0 means nothing delivered yet
    uint16 public acceptedRevision;         // 0 means nothing accepted yet
    string public revisionRequest;          // the coordinator's last note

    event DeliveryRecorded(uint16 indexed revision, bytes32 digest, address indexed who);
    event RevisionRequested(uint16 indexed revision, string note, address indexed who);
    event Accepted(uint16 indexed revision, address indexed who);

    error NotContributor();
    error NotCoordinator();
    error NothingDelivered();
    error NotNewestRevision(uint16 newest);
    error DuplicateRevision(uint16 revision);
    error DeadlinePassed(uint256 now_, uint256 deadline);
    error AlreadyAccepted(uint16 revision);

    modifier onlyContributor() {{
        if (msg.sender != contributor) revert NotContributor();
        _;
    }}
    modifier onlyCoordinator() {{
        if (msg.sender != coordinator) revert NotCoordinator();
        _;
    }}

    /// @notice The contributor records the next immutable delivery revision.
    /// @dev    Signature (uint16): the new revision number, one above the
    ///         current. Reverts for anyone but the contributor, for a repeat
    ///         of the current revision, or after acceptance already happened.
    function recordDelivery(uint16 revision) external onlyContributor {{
        if (acceptedRevision != 0) revert AlreadyAccepted(acceptedRevision);
        if (revision != currentRevision + 1) revert DuplicateRevision(revision);
        currentRevision = revision;
        emit DeliveryRecorded(revision, DECLARED_DIGEST, msg.sender);
    }}

    /// @notice The coordinator names what a revision is missing. No state
    ///         beyond the note changes: a revision request never alters or
    ///         invalidates a recorded delivery.
    /// @dev    Signature (uint16, string calldata): the revision the note
    ///         refers to and the note itself. Reverts for anyone but the
    ///         coordinator or before anything was delivered.
    function requestRevision(uint16 revision, string calldata note) external onlyCoordinator {{
        if (currentRevision == 0) revert NothingDelivered();
        if (revision != currentRevision) revert NotNewestRevision(currentRevision);
        revisionRequest = note;
        emit RevisionRequested(revision, note, msg.sender);
    }}

    /// @notice The coordinator accepts exactly the newest revision before the
    ///         deadline. Acceptance is final: it completes the record and
    ///         locks further deliveries, mirroring the off-chain protocol
    ///         where acceptance binds one exact revision.
    /// @dev    Signature (uint16): the revision being accepted. Reverts for
    ///         non-coordinators, stale revisions, a passed deadline, or when
    ///         acceptance already happened.
    function accept(uint16 revision) external onlyCoordinator {{
        if (acceptedRevision != 0) revert AlreadyAccepted(acceptedRevision);
        if (currentRevision == 0) revert NothingDelivered();
        if (revision != currentRevision) revert NotNewestRevision(currentRevision);
        if (block.timestamp > DEADLINE) revert DeadlinePassed(block.timestamp, DEADLINE);
        acceptedRevision = revision;
        emit Accepted(revision, msg.sender);
    }}
}}
"""


def explanation(agreement: dict) -> str:
    return f"""# DeliveryAcceptance — plain-language explanation

Generated by the OSS Singularity contract lab for: **{agreement['title']}**.
Synthetic example: placeholder addresses, a digest over the public synthetic
artifact, a future deadline. The lab explains signatures; it never requests
one from a wallet, deploys anything, or holds funds.

## What this contract models

The same shape as the coordination protocol you already use off-chain: a
contributor delivers immutable revisions, the coordinator reviews, a revision
request records what is missing, and acceptance binds exactly the newest
revision before a deadline. On-chain deployment is NOT part of this slice.

## Every function and its requested signature

| Function | Signature you would be asked to sign | What it establishes | Who may call |
| --- | --- | --- | --- |
| `recordDelivery(uint16 revision)` | a call naming the next revision number | that the contributor recorded revision N referencing the declared digest | contributor only |
| `requestRevision(uint16 revision, string calldata note)` | a call naming a revision and a note | that the coordinator asked for changes on exactly that revision — no state is destroyed | coordinator only |
| `accept(uint16 revision)` | a call naming the newest revision | final acceptance of exactly that revision, before the deadline | coordinator only |

## What can fail, and how each failure is named

- `NotContributor` / `NotCoordinator` — role checks at the decision point: nobody reviews or delivers for someone else.
- `DuplicateRevision` — revisions only move forward, one at a time.
- `NothingDelivered` — reviews need a delivery first.
- `NotNewestRevision` — stale revisions are refused, not silently superseded (matched history is not a current delivery).
- `DeadlinePassed` — acceptance after the deadline is refused.
- `AlreadyAccepted` — acceptance is final; replay adds nothing.

## Honest boundaries

This contract holds no funds and defines no payment. A digest proves which
bytes were declared, not quality, authorship or availability. Deployment,
testnet exercise, or any wallet interaction requires separate, explicit
authorization — nothing here signs or deploys merely because it was generated.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--agreement", required=True, help="path to an oss-solidity-lab-agreement JSON file")
    parser.add_argument("--out", required=True, help="output directory for the generated pair")
    args = parser.parse_args(argv)
    try:
        agreement = load_agreement(args.agreement)
    except (ValueError, json.JSONDecodeError) as error:
        print(f"invalid agreement: {error}", file=sys.stderr)
        return 1
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "DeliveryAcceptance.sol").write_text(contract_source(agreement), encoding="utf-8")
    (out / "DeliveryAcceptance.explained.md").write_text(explanation(agreement), encoding="utf-8")
    print(f"generated DeliveryAcceptance.sol and DeliveryAcceptance.explained.md in {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
